### ISSUE TITLE
Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by hamochigames** [mob-sakai/unity-activate#7]
Few weeks back then, it is working.
Today it shows "Navigation timeout of 30000 ms exceeded" error when I tried to renew the license.

- Used in Github Action
- Unity Version 2020.3.15f2
- Personal license
- Activate with authenticator key

**Logs**
```
Run unity-activate --username "***" -*** --key "***" "Unity_v***.alf"
Start activating 'Unity_v***.alf'
  > goto manual activation page
  > enter the username and password
  > login
  > upload alf file
Navigation timeout of 30000 ms exceeded
Run `unity-activate --help` to show help.
Error: Process completed with exit code 1.
```

**My .yml File**
```
name: Renew Unity license
on:
  workflow_dispatch: {}
env:
  # License
  ULF_FILE: Unity_v2020.x.ulf
  # Project
  UNITY_VERSION: ${{ secrets.UNITY_VERSION }}
jobs:
  request_alf:
    name: Request .alf file 🔑
    runs-on: ubuntu-latest
    outputs:
      alf: ${{ steps.output.outputs.alf }}
    steps:
      - name: Request manual activation file
        id: alfFile
        uses: game-ci/unity-request-activation-file@main
        with:
          unityVersion: ${{ env.UNITY_VERSION }}

      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.alfFile.outputs.filePath }}
          path: ${{ steps.alfFile.outputs.filePath }}

      - name: Output
        id: output
        run: |
          echo "::set-output name=alf::${{ steps.alfFile.outputs.filePath }}"
  acquire_ulf:
    needs: [request_alf]
    name: Acquire .ulf file 🔑
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Download .alf artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.request_alf.outputs.alf }}

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      #- name: Install node package, `unity-license-activate`
      #  run: npm install --global unity-license-activate
      
      - name: Install node package, `unity-activate`
        run: npm install --global unity-activate

      - name: Install node package, `unity-verify-code`
        run: npm install --global unity-verify-code
        
      - name: Activate license
        run: unity-activate --username "${{ secrets.UNITY_EMAIL }}" --password "${{ secrets.UNITY_PASSWORD }}" --key "${{ secrets.UNITY_AUTHENTICATOR_KEY }}" "Unity_v${{ env.UNITY_VERSION }}.alf"

      #- name: Activate the license
      #  continue-on-error: true
      #  run: unity-license-activate "${{ secrets.UNITY_EMAIL }}" "${{ secrets.UNITY_PASSWORD }}" "${{ needs.request_alf.outputs.alf }}" "${{ secrets.UNITY_AUTHENTICATOR_KEY }}"

      - name: Read ulf
        id: ulfRead
        uses: juliangruber/read-file-action@v1.1.4
        with:
          path: ${{ env.ULF_FILE }}

      - name: Update secret UNITY_LICENSE
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'UNITY_LICENSE'
          value: '${{ steps.ulfRead.outputs.content }}'
          token: ${{ secrets.ACCESS_TOKEN }}
```

**Comment by mob-sakai** [comment]
@hamochigames 
Interesting action :+1:

- A new version has been released, which may resolve the issue.
  - Updated `puppeteer` package from `5.4.0` to `11.0.0`. 
- If the issue is not resolved, use `-d` or `--debug` option to show the detailed log.

**Comment by tfgstudios** [comment]
hey. the issue is Unity shows the "We've updated our subprocessors list" popup, and that's where it hangs (just before processing the license file). hope this helps

**Comment by mob-sakai** [comment]
@tfgstudios 
Thanks for the info!

**Comment by tfgstudios** [comment]
> @tfgstudios Thanks for the info!

Thanks for the quick update! It seems, however, that the issue persists. Here's what happens:

I see "> login"
Then "waitForNavigation"
and it starts hanging. 
I also ran it again via gui to see it in action and the popup wasn't closed, but what's important here is I don't see the "  > close update dialog" message either, so maybe your code works but it's never reached

**Comment by mob-sakai** [comment]
@tfgstudios 
The fixed version (`1.3.4`) has been released!

**Comment by hamochigames** [comment]
Tested latest version 1.3.4, still not working

```
Run unity-activate --username "***" -*** --key "***" "Unity_v***.alf"
Start activating 'Unity_v***.alf'
  > goto manual activation page
  > valid the username and password
  > close cookie dialog
  > enter the username and password
  > login
  > close update dialog
  > upload alf file
Navigation timeout of 30000 ms exceeded
Run `unity-activate --help` to show help.
Error: Process completed with exit code 1.
```

**Comment by mob-sakai** [comment]
@hamochigames @tfgstudios 
The fixed version (`1.3.5`) has been released!
It adds a waiting time for some actions.

**Comment by hamochigames** [comment]
Yup it is working now.
I modified my action accordingly.

```
name: Renew Unity License
on:
  schedule:
    - cron: "* * * * 0" # weekly
  workflow_dispatch: {}
env:
  ULF_FILE: Unity_v2020.x.ulf
  UNITY_VERSION: ${{ secrets.UNITY_VERSION }}
jobs:
  acquire_ulf:
    runs-on: ubuntu-latest
    steps:
      - name: Install node package, `unity-activate`
        run: npm install --global unity-activate
      - name: Request manual activation file
        id: alfFile
        uses: game-ci/unity-request-activation-file@main
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
      - name: Activate license
        id: activate
        run: unity-activate --username "${{ secrets.UNITY_EMAIL }}" --password "${{ secrets.UNITY_PASSWORD }}" --key "${{ secrets.UNITY_AUTHENTICATOR_KEY }}" -d "${{ steps.alfFile.outputs.filePath }}"
      - name: Read ulf
        id: ulfRead
        uses: juliangruber/read-file-action@v1.1.4
        with:
          path: ${{ env.ULF_FILE }}
      - name: Update secret UNITY_LICENSE
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'UNITY_LICENSE'
          value: '${{ steps.ulfRead.outputs.content }}'
          token: ${{ secrets.ACCESS_TOKEN }}
```

**Comment by mob-sakai** [comment]
@hamochigames 

:+1:
Instead of `npm install --global unity-activate` and `unity-activate`, you can use `npx unity-activate` for more simplicity.

```yaml
name: Renew Unity License
on:
  schedule:
    - cron: "* * * * 0" # weekly
  workflow_dispatch: {}
env:
  ULF_FILE: Unity_v2020.x.ulf
  UNITY_VERSION: ${{ secrets.UNITY_VERSION }}
jobs:
  acquire_ulf:
    runs-on: ubuntu-latest
    steps:
#     - name: Install node package, `unity-activate`
#       run: npm install --global unity-activate
      - name: Request manual activation file
        id: alfFile
        uses: game-ci/unity-request-activation-file@main
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
      - name: Activate license
        id: activate
#       run: unity-activate --username "${{ secrets.UNITY_EMAIL }}" --password "${{ secrets.UNITY_PASSWORD }}" --key "${{ secrets.UNITY_AUTHENTICATOR_KEY }}" -d "${{ steps.alfFile.outputs.filePath }}"
        run: npx unity-activate --username "${{ secrets.UNITY_EMAIL }}" --password "${{ secrets.UNITY_PASSWORD }}" --key "${{ secrets.UNITY_AUTHENTICATOR_KEY }}" -d "${{ steps.alfFile.outputs.filePath }}"
      - name: Read ulf
        id: ulfRead
        uses: juliangruber/read-file-action@v1.1.4
        with:
          path: ${{ env.ULF_FILE }}
      - name: Update secret UNITY_LICENSE
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'UNITY_LICENSE'
          value: '${{ steps.ulfRead.outputs.content }}'
          token: ${{ secrets.ACCESS_TOKEN }}
```
